[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20", CI = "false" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self' https:; \
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://pagead2.googlesyndication.com https://www.google-analytics.com; \
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
      img-src 'self' https: data:; \
      font-src 'self' https://fonts.gstatic.com data:; \
      connect-src 'self' https://api.guerrillamail.com https://www.google-analytics.com; \
      frame-src 'self' https://googleads.g.doubleclick.net https://www.google.com; \
      object-src 'none'
    """